// Generated by CoffeeScript 1.3.3
(function() {
  var fpdsTemplate;

  fpdsTemplate = _.template("<li>\n  <dl>\n    <dt>Contract ID</dt>\n    <dd><%= contract_id %></dd>\n\n    <dt>Date Signed</dt>\n    <dd><%= date_signed %></dd>\n\n    <dt>Office Name</dt>\n    <dd><%= contracting_office_name %></dt>\n\n    <dt>Agency</dt>\n    <dd><%= contracting_agency %></dd>\n\n    <dt>Action Obligation</dt>\n    <dd><%= action_obligation %></dd>\n  </dl>\n</li>");

  $(document).on("submit", "#search-form", function(e) {
    var dsbsUrl, duns, dunsUrl, fpdsUrl;
    e.preventDefault();
    duns = $(this).find("input").val();
    if (!duns) {
      return;
    }
    $("dd").removeClass('loaded');
    $(".results").fadeIn(300);
    dunsUrl = "http://rfpez-apis.presidentialinnovationfellows.org/exclusions?duns=" + duns;
    $.getJSON(dunsUrl, function(r) {
      var dd;
      dd = $("[data-epls]");
      dd.find(".result").attr('href', dunsUrl).text(r.results.length ? "Yes" : "No");
      return dd.addClass("loaded");
    });
    dsbsUrl = "http://rfpez-apis.presidentialinnovationfellows.org/bizs?duns=" + duns;
    $.getJSON(dsbsUrl, function(r) {
      var dd, key, result, _ref;
      result = (_ref = r.results) != null ? _ref[0] : void 0;
      dd = $("[data-dsbs]");
      dd.find(".result").find("a.yesno").attr('href', dsbsUrl).text(result ? "Yes" : "No");
      if (result) {
        $("#dsbs-table").show();
        for (key in result) {
          $("#dsbs-table td[data-key=" + key + "]").text(result[key]);
        }
      } else {
        $("#dsbs-table").hide();
      }
      return dd.addClass("loaded");
    });
    fpdsUrl = "http://rfpez-apis.presidentialinnovationfellows.org/awards?q=" + duns + "&per_page=100000";
    return $.getJSON(fpdsUrl, function(r) {
      var dd, hasResults, result, _i, _len, _ref, _ref1;
      hasResults = (_ref = r.results) != null ? _ref[0] : void 0;
      dd = $("[data-fpds]");
      dd.find(".result").find("a.yesno").attr('href', fpdsUrl).text(hasResults ? "Yes" : "No");
      if (hasResults) {
        $("#fpds-list").show();
        _ref1 = r.results;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          result = _ref1[_i];
          $("#fpds-list").append(fpdsTemplate(result));
        }
      } else {
        $("#fpds-list").hide();
      }
      return dd.addClass("loaded");
    });
  });

}).call(this);
